baseurl = "https://blog.unhappyfolk.org"
languageCode = "en-us"
theme = "hello-friend"
paginate = 15
disableRSS = false

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4
  # Enable to show reading time in minutes for posts
  showReadingTime = false
  author = "mhashim6"
  images = ['img/preview.png']
  header = "The Unhappy Folk's Literature"
  [params.logo]
    logoText = "The Unhappy Folk's Literature"
    logoHomeLink = "/"
    path = "/img/logo.svg"
    alt = "The Unhappy Folk's Literature"

[languages]
  [languages.en]
    title = "The Unhappy Folk's Literature"
    subtitle = "Blog, Timeless, Placeless."
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read"
    readOtherPosts = "Read other publications"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
        logoText = "The Unhappy Folk's Literature"
        logoHomeLink = "/"
    # or
    #
        path = "/img/logo.svg"
        alt = "The Unhappy Folk's Literature"

    [languages.en.menu]
    #   [[languages.en.menu.main]]
    #     identifier = "about"
    #     name = "About"
    #     url = "/about"
    #   [[languages.en.menu.main]]
    #     identifier = "showcase"
    #     name = "Showcase"
    #     url = "/showcase"
      [[languages.en.menu.main]]
        identifier = "translation"
        name = "عربي"
        url = "/ar"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "follow"
        name = "Follow Us"
        weight = 2
        url = "https://t.me/unhappyfolk/"
      # [[languages.en.menu.main]]
      #   identifier = "website"
      #   name = "Website"
      #   weight = 2
      #   url = "https://unhappyfolk.org/"
      [[languages.en.menu.main]]
        identifier = "rss"
        name = "RSS"
        weight = 3
        url = "https://blog.unhappyfolk.org/index.xml"
  [languages.ar]
    title = "The Unhappy Folk's Literature (مترجمة)"
    languagedirection = 'rtl'
    writtenBy = "ترجمة"
    readMore = "اقرأ"
    readOtherPosts = "اقرأ مقالات أخرى"
    newerPosts = "مقالات أحدث"
    olderPosts = "مقالات أقدم"
  
    [languages.ar.menu]
      [[languages.ar.menu.main]]
        identifier = "translation"
        name = "English"
        url = "/"
        weight = 1
      [[languages.ar.menu.main]]
        identifier = "follow"
        name = "تابعنا"
        weight = 1
        url = "https://t.me/unhappyfolk/"
      # [[languages.ar.menu.main]]
      #   identifier = "website"
      #   name = "موقعنا"
      #   weight = 2
      #   url = "https://unhappyfolk.org/"
      [[languages.ar.menu.main]]
        identifier = "rss"
        name = "RSS"
        weight = 3
        url = "https://blog.unhappyfolk.org/index.xml"
